# Generated by Django 3.1.7 on 2021-03-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
