# Generated by Django 3.1.7 on 2021-03-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizManager', '0003_auto_20210329_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='category',
        ),
    ]
