# Generated by Django 3.1.7 on 2021-04-30 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizManager', '0008_auto_20210430_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='quiz',
            name='assigned_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
