# Generated by Django 3.1.7 on 2021-05-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizManager', '0009_auto_20210430_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
