# Generated by Django 3.1.7 on 2021-05-04 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuizManager', '0010_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
