# Generated by Django 3.1.7 on 2021-05-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizManager', '0012_auto_20210504_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.CharField(max_length=300)),
                ('choice', models.CharField(max_length=300)),
                ('correct', models.BooleanField()),
            ],
        ),
    ]
