# Generated by Django 3.1.7 on 2021-05-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizManager', '0013_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='user',
            field=models.CharField(default='test', max_length=300),
            preserve_default=False,
        ),
    ]
